version: '3.8'
services:
  moneydb:
    image: mysql:8.3
    restart: 'unless-stopped'
    environment:
      MYSQL_ROOT_PASSWORD: Mysql2024!
      MYSQL_DATABASE: moneydb
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql